In [ ]:
import numpy as np

# From Python list
arr = np.array([1, 2, 3, 4, 5])

# 2D array (matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Using built-in functions
zeros = np.zeros((3, 4))         # 3x4 array of zeros
ones = np.ones((2, 3))           # 2x3 array of ones
range_arr = np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]
linspace = np.linspace(0, 1, 5)  # 5 evenly spaced values from 0 to 1
identity = np.eye(3)             # 3x3 identity matrix
random_arr = np.random.rand(3, 4)# Random values between 0 and 1


In [ ]:
display(arr)

display(arr_2d)

display(zeros)

display(ones)

display(range_arr)

display(ones = np.zeros)

array([1, 2, 3, 4, 5])

array([[1, 2, 3],
       [4, 5, 6]])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[1., 1., 1.],
       [1., 1., 1.]])

array([0, 2, 4, 6, 8])

In [ ]:
zeros = np.zeros((0,0))         # 0x0 array of zeros

In [ ]:
display(zeros)

array([], shape=(0, 0), dtype=float64)

In [ ]:
ones = np.ones((2, 3))           # 2x3 array of ones

In [ ]:
display(ones)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
range_arr = np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]

In [ ]:
display(range_arr)

array([0, 2, 4, 6, 8])

In [ ]:
arr=np.arange(10)
print(arr)
display(arr)

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr=np.arange(5,)
print(arr)

[0 1 2 3 4]


In [ ]:
arr=np.arange(-10)
print(arr)

[]


In [ ]:
sequence = np.arange(0,1.2,0.2)
print("float point sequence: ", sequence)

float point sequence:  [0.  0.2 0.4 0.6 0.8 1. ]


In [ ]:
sequence=np.arange(0,24,3)
print(sequence)

[ 0  3  6  9 12 15 18 21]


In [ ]:
filtered = sequence[sequence > 10]
print("filtered :",filtered)

filtered : [12 15 18 21]


In [ ]:
filtered = sequence[sequence % 2 == 0]
print("filtered :",filtered)

filtered : [ 0  6 12 18]


In [ ]:
filtered = sequence[(sequence > 2) & (sequence < 20)]
print("filtered :",filtered)

filtered : [ 3  6  9 12 15 18]


In [ ]:
import numpy as np

# From Python list
arr = np.array([1, 2, 3, 4, 5])

# 2D array (matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Using built-in functions
zeros = np.zeros((3, 4))         # 3x4 array of zeros
ones = np.ones((2, 3))           # 2x3 array of ones
range_arr = np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]
linspace = np.linspace(0, 1, 5)  # 5 evenly spaced values from 0 to 1
identity = np.eye(3)             # 3x3 identity matrix
random_arr = np.random.rand(3, 4)# Random values between 0 and 1

In [ ]:
linspace = np.arange(10, 20, 5)  # 5 evenly spaced values from 0 to 1
display(linspace)

array([10, 15])

In [ ]:
linspace = np.linspace(10, 20, 5)  # 5 evenly spaced values from 0 to 1
display(linspace)

array([10. , 12.5, 15. , 17.5, 20. ])

In [ ]:
linspace = np.linspace(10, 20, 2)
display(linspace)

array([10., 20.])

In [ ]:
linspace = np.linspace(10, 20)
display(linspace)

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [ ]:
import numpy as np

# Generate 10 numbers between 0 and 1
array_without_endpoint = np.linspace(0, 1, num=10, endpoint=True)

print(array_without_endpoint)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
import numpy as np

# Generate 10 numbers between 0 and 1
array_without_endpoint = np.linspace(0, 1, num=10, endpoint=False)

print(array_without_endpoint)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [ ]:
import numpy as np

# Generate 5 numbers between 0 and 10 and return the step size
array, step = np.linspace(17, 26, num=9, retstep=True)
print(array)
print("Step Size:", step)

[17.    18.125 19.25  20.375 21.5   22.625 23.75  24.875 26.   ]
Step Size: 1.125


In [ ]:
import numpy as np

# Create a 2D array of 5x5 numbers between 0 and 1
array_2d = np.linspace(0, 1, num=25)

print(array_2d)

[0.         0.04166667 0.08333333 0.125      0.16666667 0.20833333
 0.25       0.29166667 0.33333333 0.375      0.41666667 0.45833333
 0.5        0.54166667 0.58333333 0.625      0.66666667 0.70833333
 0.75       0.79166667 0.83333333 0.875      0.91666667 0.95833333
 1.        ]


In [ ]:
import numpy as np

# Create a 2D array of 5x5 numbers between 0 and 1
array_2d = np.linspace(0, 1, num=25).reshape(5, 5)

print(array_2d)

[[0.         0.04166667 0.08333333 0.125      0.16666667]
 [0.20833333 0.25       0.29166667 0.33333333 0.375     ]
 [0.41666667 0.45833333 0.5        0.54166667 0.58333333]
 [0.625      0.66666667 0.70833333 0.75       0.79166667]
 [0.83333333 0.875      0.91666667 0.95833333 1.        ]]


In [ ]:
import numpy as np
# 2D Array (matrix) - farm grid
farm_grid = np.array([
    [2500, 2600, 2700],
    [2800, 2900, 3000],
    [2400, 2500, 2600]])
print(f"\nFarm Grid:\n{farm_grid}")
print(f"Shape: {farm_grid.shape}")  # 3 rows, 3 columns


Farm Grid:
[[2500 2600 2700]
 [2800 2900 3000]
 [2400 2500 2600]]
Shape: (3, 3)


In [ ]:
import numpy as np

# Data
soil_ph = np.array([6.2, 5.8, 7.1, 6.5, 5.5, 6.8, 7.3, 6.0, 5.9, 6.7])

# Calculations
mean_ph = np.mean(soil_ph)
median_ph = np.median(soil_ph)
min_ph = np.min(soil_ph)
max_ph = np.max(soil_ph)
std_dev = np.std(soil_ph)

print(f"Mean pH: {mean_ph:.2f}")
print(f"Median pH: {median_ph:.2f}")
print(f"Range: {min_ph} - {max_ph}")
print(f"Standard Deviation: {std_dev:.2f}")


Mean pH: 6.38
Median pH: 6.35
Range: 5.5 - 7.3
Standard Deviation: 0.56


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[3])

4


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [ ]:
#2D array
import numpy as np

arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print('5th element on 2st row: ', arr[1, 4])
print('5th element on 2st row: ', arr[1, -1])
print('2nd element on 2st row: ', arr[1, 1])

2nd element on 1st row:  2
5th element on 2st row:  10
5th element on 2st row:  10
2nd element on 2st row:  7


In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]],
                 [[7, 8, 9],[10, 11, 12]]])

print(arr[0, 1, 2])
print(arr[1, 1, 2])
print(arr[1,1,1])
print(arr[-1,-1,-1])
print(arr[-2,1,-1])
print(arr[0,0])

print(arr[1])

6
12
11
12
6
[1 2 3]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
yields = np.array([2500, 2800, 3100, 2900, 2700])

# Access elements
print(f"First yield: {yields[0]}")
print(f"Last yield: {yields[-1]}")
print(f"First 3 yields: {yields[:3]}")

First yield: 2500
Last yield: 2700
First 3 yields: [2500 2800 3100]


In [ ]:
import numpy as np

# 2D Array (matrix) - farm grid
farm_grid = np.array(
       [[2500, 2600, 2700],
        [2800, 2900, 3000],
        [2400, 2500, 2600]])

# 2D indexing
print(f"Center plot yield: {farm_grid[1, 1]}")
print(f"First row: {farm_grid[0]}")
print(f"Last column: {farm_grid[:, -1]}")
print(f"Last column: {farm_grid[:, 2]}")
print(f"2nd column column: {farm_grid[:, -2]}")

Center plot yield: 2900
First row: [2500 2600 2700]
Last column: [2700 3000 2600]
Last column: [2700 3000 2600]
2nd column column: [2600 2900 2500]


In [ ]:
#numpy array slicing
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])
print(arr[:4])
print(arr[-3:-1])

[5 6 7]
[1 2 3 4]
[5 6]


In [ ]:
#Return every other element from index 1 to index 5:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:1]) #2 is step

[2 3 4 5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])


[1 3 5 7]


In [ ]:
#2d slicing
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4:2])

[7 9]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
#Get the data type of an array object:

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [ ]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)


[1 2 3]
int64


In [ ]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [ ]:
import numpy as np

# 10 soil samples with pH values
soil_ph = np.array([6.2, 5.8, 7.1, 6.5, 5.5,
                    6.8, 7.3, 6.0, 5.9, 6.7])

# Your tasks:
# 1. Find the mean pH
# 2. Count samples that are acidic (pH < 6.5)
# 3. Find which sample has the highest pH
# 4. Normalize pH to 0-1 range using (x - min)/(max - min)
mean = soil_ph.mean()
acidic_count = np.sum(soil_ph < 6.5)
highest_ph = soil_ph.max()
normalized_ph = (soil_ph - soil_ph.min()) / (soil_ph.max() - soil_ph.min())
print("mean value =",mean)
print("acidic_count=" , acidic_count)
print("Maximum pH =",highest_ph)
print("normalized pH=" , normalized_ph)

mean value = 6.380000000000001
acidic_count= 5
Maximum pH = 7.3
normalized pH= [0.38888889 0.16666667 0.88888889 0.55555556 0.         0.72222222
 1.         0.27777778 0.22222222 0.66666667]


In [ ]:
import numpy as np

# 10 soil samples with pH values
soil_ph = np.array([6.2, 5.8, 7.1, 6.5, 5.5,
                    6.8, 7.3, 6.0, 5.9, 6.7])

# Your tasks:
# 1. Find the mean pH
# 2. Count samples that are acidic (pH < 6.5)
# 3. Find which sample has the highest pH
# 4. Normalize pH to 0-1 range using (x - min)/(max - min)

mean = soil_ph.mean()
acidic_count = np.sum(soil_ph < 6.5)
highest_ph = soil_ph.max()
normalized_ph = (soil_ph - soil_ph.min()) / (soil_ph.max() - soil_ph.min())
print(mean)
print(acidic_count)
print(highest_ph)
print(normalized_ph)

6.380000000000001
5
7.3
[0.38888889 0.16666667 0.88888889 0.55555556 0.         0.72222222
 1.         0.27777778 0.22222222 0.66666667]


In [ ]:
import numpy as np

# Creating a rank 1 Array
arr = np.array([1, 2, 3])
print(arr)

# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

# Creating an array from tuple
arr = np.array((1, 3, 2))
print(arr)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[1 3 2]


In [ ]:
#accessing an array
import numpy as np

arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

# Printing a range of Array
# with the use of slicing method
arr2 = arr[:2, ::2]
print ("first 2 rows and alternate columns(0 and 2):\n", arr2)


first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]


In [ ]:
import numpy as np

arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

# Printing a range of Array
# with the use of slicing method
arr2 = arr[2:, 1::2,]
print ("last 2 rows and alternate columns(1 and 3):\n", arr2)

last 2 rows and alternate columns(1 and 3):
 [[ 0.  8.]
 [-7.  2.]]


In [ ]:
import numpy as np

arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
arr2 = arr[:,-2:]
print ("all rows and last 2 columns(3 and 4):\n", arr2)

all rows and last 2 columns(3 and 4):
 [[0. 4.]
 [6. 0.]
 [7. 8.]
 [4. 2.]]


In [ ]:

# Printing elements at
# specific Indices
arr3 = arr[[1, 1, 0, 3],
                [3, 2, 1, 0]]
print ("\nElements at indices (1, 3), "
    "(1, 2), (0, 1), (3, 0):\n", arr3)
arr3 = arr[1,3]
print(arr3)


Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]
0.0


In [ ]:
# Printing elements at
# specific Indices
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

arr3 = arr[[1, 1, 0, 3],
                [3, 2, 1, 0]]
print ("\nElements at indices (1, 3), "
    "(1, 2), (0, 1), (3, 0):\n", arr3)

arr4 = arr[1,3]
print("\nElements at index (1, 3) is",arr4)

arr5 = arr[1,2]
print("\nElements at index (1, 2) is",arr5)

arr6 = arr[0,1]
print("\nElements at index (0, 1) is",arr6)

arr7 = arr[3,0]
print("\nElements at index (3, 0) is",arr7)


Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]

Elements at index (1, 3) is 0.0

Elements at index (1, 2) is 6.0

Elements at index (0, 1) is 2.0

Elements at index (3, 0) is 3.0


In [ ]:
import numpy as np

# Defining Array 1
a = np.array([[1, 2],
              [3, 4]])

# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])

# Adding 1 to every element
print ("Adding 1 to every element:", a + 1)

# Subtracting 2 from each element
print ("\nSubtracting 2 from each element:", b - 2)

# sum of array elements
# Performing Unary operations
print ("\nSum of all array elements: ", a.sum())

# Adding two arrays
# Performing Binary operations
print ("\nArray sum:\n", a + b)

Adding 1 to every element: [[2 3]
 [4 5]]

Subtracting 2 from each element: [[ 2  1]
 [ 0 -1]]

Sum of all array elements:  10

Array sum:
 [[5 5]
 [5 5]]


In [ ]:
import numpy as np

# Integer datatype
x = np.array([1, 2])
print(x.dtype)

# Float datatype
x = np.array([1.0, 2.0])
print(x.dtype)

# Forced Datatype
x = np.array([1, 2], dtype = np.int64)
print(x.dtype)

int64
float64
int64


In [ ]:
import numpy as np

# First Array
arr1 = np.array([[4, 7], [2, 6]],
                 dtype = np.float64)

# Second Array
arr2 = np.array([[3, 6], [2, 8]],
                 dtype = np.float64)

# Addition of two Arrays
Sum = np.add(arr1, arr2)
print("\nsum of 2 array: ",Sum)

# Addition of all Array elements
Sum1 = np.sum(arr1)
print("\nsum of elements of arr1: ",Sum1)

# Square root of Array
Sqrt = np.sqrt(arr1)
print("\nsquare root of arr1: ", Sqrt)

# Transpose of Array
Trans_arr = arr1.T
print("\ntranspose of arr1: ", Trans_arr)


sum of 2 array:  [[ 7. 13.]
 [ 4. 14.]]

sum of elements of arr1:  19.0

square root of arr1:  [[2.         2.64575131]
 [1.41421356 2.44948974]]

transpose of arr1:  [[4. 2.]
 [7. 6.]]


In [ ]:
yields = np.array([2500, 2800, 3100, 2900, 2700])

farm_grid = np.array([
    [2500, 2600, 2700],
    [2800, 2900, 3000],
    [2400, 2500, 2600]
])

# === ARRAY OPERATIONS ===
print("\n=== Array Operations ===")

# Math on entire arrays (vectorized!)
yields_tons = yields / 1000
print(f"Yields in tons: {yields_tons}")

# Bonus calculation
bonus = np.where(yields > 2800, 500, 0)
print(f"Bonus per plot: {bonus}")

# Statistics
print(f"\nTotal yield: {np.sum(yields)} kg")
print(f"Average: {np.mean(yields):.0f} kg")
print(f"Std Dev: {np.std(yields):.0f} kg")
print(f"Max: {np.max(yields)} kg, Min: {np.min(yields)} kg")

# Boolean filtering
high_yield_plots = yields[yields > 2700]
print(f"High yield plots (>2700): {high_yield_plots}")


=== Array Operations ===
Yields in tons: [2.5 2.8 3.1 2.9 2.7]
Bonus per plot: [  0   0 500 500   0]

Total yield: 14000 kg
Average: 2800 kg
Std Dev: 200 kg
Max: 3100 kg, Min: 2500 kg
High yield plots (>2700): [2800 3100 2900]


In [ ]:
#Make a copy, change the original array, and display both arrays:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
#Make a view, change the original array, and display both arrays:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x = arr.copy()
x[0] = 31

print(arr)
print(x)

[1 2 3 4 5]
[31  2  3  4  5]


In [ ]:
#Print the value of the base attribute to check if an array owns it's data or not:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [ ]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])

for element in np.nditer(arr, order='f'):
    print("column major:", element)
for element in np.nditer(arr, order='c'):
    print("\nrow major :", element)

column major: 1
column major: 3
column major: 2
column major: 4

row major : 1

row major : 2

row major : 3

row major : 4


In [ ]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])

for element in np.nditer(arr, order='F'):
    print(element)

newarr =arr.reshape(2,2)
print(newarr)

1
3
2
4
[[1 2]
 [3 4]]


In [ ]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])

# Get elements in Fortran order and reshape them into a 2D array
fortran_ordered_2d = arr.flatten(order='F').reshape(arr.shape)

print("Elements in Fortran order (reshaped to 2D):")
print(fortran_ordered_2d)

Elements in Fortran order (reshaped to 2D):
[[1 3]
 [2 4]]


In [ ]:
#step size
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [ ]:
#Enumerate on following 1D arrays elements:

import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [ ]:
#Enumerate on following 1D arrays elements:

import numpy as np

arr = np.array([[1, 2, 3]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3


In [ ]:
arr = np.array([[[1, 2, 3]]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [ ]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

for idx, x in np.ndenumerate(arr):
  print(idx, x)

1
2
3
4
5
6
7
8
(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8


In [ ]:
import numpy as np

# Create a 2D array
arr = np.array([[10, 20], [30, 40]])

# Enumerate through rows
for idx, row in enumerate(arr):
    print(f"Row {idx}: {row}")

Row 0: [10 20]
Row 1: [30 40]


In [ ]:
#joining
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
#Join two 2-D arrays along rows (axis=1):

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
import numpy as np

arr1 = np.array([[50, 60]])

arr2 = np.array([[70, 80]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[50 60]
 [70 80]]


In [ ]:
import numpy as np
std1 = [50, 60]
std2 = [70, 90]
marks = np.sum((std1, std2), axis = 0)
print(marks)
marks = np.sum((std1, std2), axis = 1)
print(marks)
mark = np.max(marks)
print(mark)

[120 150]
[110 160]
160


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
import numpy as np

# Crop yields for 4 farms over 5 seasons (in tons)
crop_yields = np.array([
    [12.5, 13.2, 14.1, 13.8, 15.2],  # Farm 1 - North Region
    [10.3, 11.5, 10.8, 12.1, 11.9],  # Farm 2 - South Region
    [15.1, 14.8, 16.2, 15.5, 16.8],  # Farm 3 - East Region
    [11.2, 10.9, 12.3, 11.7, 12.8]   # Farm 4 - West Region
])

print('Crop Yields Array (tons):')
print(crop_yields)
print(f'\nShape: {crop_yields.shape}')
print(f'Data type: {crop_yields.dtype}')
print(f'Total elements: {crop_yields.size}')
print(f'Number of dimensions: {crop_yields.ndim}')

# Agricultural analysis operations
total_yield = np.sum(crop_yields)
avg_yield_per_farm = np.mean(crop_yields, axis=1)
avg_yield_per_season = np.mean(crop_yields, axis=0)
max_yield = np.max(crop_yields)
min_yield = np.min(crop_yields)

print(f'\nTotal production: {total_yield} tons')
print(f'Average per farm: {avg_yield_per_farm} tons')
print(f'Average per season: {avg_yield_per_season} tons')
print(f'Maximum yield: {max_yield} tons')
print(f'Minimum yield: {min_yield} tons')

# Find best performing farm
best_farm = np.argmax(avg_yield_per_farm)
print(f'\nBest performing farm: Farm {best_farm + 1}')
print(f'Their average yield: {avg_yield_per_farm[best_farm]:.2f} tons')

Crop Yields Array (tons):
[[12.5 13.2 14.1 13.8 15.2]
 [10.3 11.5 10.8 12.1 11.9]
 [15.1 14.8 16.2 15.5 16.8]
 [11.2 10.9 12.3 11.7 12.8]]

Shape: (4, 5)
Data type: float64
Total elements: 20
Number of dimensions: 2

Total production: 262.7 tons
Average per farm: [13.76 11.32 15.68 11.78] tons
Average per season: [12.275 12.6   13.35  13.275 14.175] tons
Maximum yield: 16.8 tons
Minimum yield: 10.3 tons

Best performing farm: Farm 3
Their average yield: 15.68 tons


In [ ]:
#Split the array in 3 parts:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 7)
print(newarr)
print(newarr[6])

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int64)]
[]


In [ ]:
#Split the array in 3 parts:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.split(arr, 3)

print(newarr)
print(newarr[0])
print(newarr[1:3])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[array([3, 4]), array([5, 6])]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)
print(newarr[0])
print(newarr[1])
print(newarr[2])
print(newarr[-2])
print(newarr[1:2])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]
[3 4]
[array([3, 4])]


In [ ]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
#Split the 2-D array into three 2-D arrays along columns.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
#Use the hsplit() method to split the 2-D array into three 2-D arrays along columns.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.vsplit(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
#Find the indexes where the value is 4:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 7)

print(x)

(array([], dtype=int64),)


In [ ]:
#Find the indexes where the values are even:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [ ]:
#Find the indexes where the value 7 should be inserted:

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 8.5)

print(x)

3


In [ ]:
#Find the indexes where the value 7 should be inserted, starting from the right:

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [ ]:
#Find the indexes where the value 7 should be inserted, starting from the left:

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='left')

print(x)

1


In [ ]:
# the indexes where the values 2, 4, and 6 should be inserted:

import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [ ]:
# Optimized Python program for implementation of Bubble Sort
def bubbleSort(arr):
    n = len(arr)

    # Traverse through all array elements
    for i in range(n):
        swapped = False

        # Last i elements are already in place
        for j in range(0, n-i-1):

            # Traverse the array from 0 to n-i-1
            # Swap if the element found is greater
            # than the next element
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
                swapped = True
        if (swapped == False):
            break

# Driver code to test above
if __name__ == "__main__":
    arr = [64, 34, 25, 12, 22, 11, 90]

    bubbleSort(arr)

    print("Sorted array:")
    for i in range(len(arr)):
        print("%d" % arr[i], end=" ")

Sorted array:
11 12 22 25 34 64 90 

In [ ]:
#Sort the array:

import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [ ]:
#Sort the array:

import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr)[::-1])
print(np.sort(arr)[::])
print(np.sort(arr)[::-2])
print(np.sort(arr)[::2])


[3 2 1 0]
[0 1 2 3]
[3 1]
[0 2]


In [ ]:
#Sort the array alphabetically:

import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))
print(np.sort(arr)[::-1])
print(np.sort(arr)[::2])
print(np.sort(arr)[::-2])
print(np.sort(arr)[1:2])

['apple' 'banana' 'cherry']
['cherry' 'banana' 'apple']
['apple' 'cherry']
['cherry' 'apple']
['banana']


In [ ]:
#Sort a boolean array:

import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [ ]:
#Sort a 2-D array:

import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))
print(np.sort(arr)[::-1])

[[2 3 4]
 [0 1 5]]
[[0 1 5]
 [2 3 4]]


In [ ]:
#Create an array from the elements on index 0 and 2:

import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [ ]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [ ]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [ ]:
import numpy as np

sales = np.array([1200, 1500, 1100, 1800, 1700, 1600, 1400])
print(sales)

print("Total Sales:", np.sum(sales))

avg = np.mean(sales)
print("Average Sales:", avg)

print("Sales above 1500:", sales[sales > 1500])

print("Highest Sale:", np.max(sales))
print("Lowest Sale:", np.min(sales))

print("Low Sales Days:", np.sum(sales < avg))

[1200 1500 1100 1800 1700 1600 1400]
Total Sales: 10300
Average Sales: 1471.4285714285713
Sales above 1500: [1800 1700 1600]
Highest Sale: 1800
Lowest Sale: 1100
Low Sales Days: 3


In [ ]:
# Addition of Matrices
import numpy as np
Array1 = np.matrix( [ [ 1, 2, 3 ],
                      [ 4, 5, 6 ],
                      [ 7, 8, 9 ] ] )
Array2 = np.matrix( [ [ 10, 11, 12 ],
                      [ 13, 14, 15 ],
                      [ 16, 17, 18 ] ] )
print("Output : \n",Array1+ Array2)

Output : 
 [[11 13 15]
 [17 19 21]
 [23 25 27]]


In [7]:
# Multiply or divide a matrix by a scalar
import numpy as np
Array = np.matrix( [ [ 1, 2, 3 ],
                      [ 4, 5, 6 ],
                      [ 7, 8, 9 ] ] )
multiplyByScalar = 2* Array
DivideByScalar = Array / 8
print("Output of product between an Array and scalar : \n", multiplyByScalar)
print("Output of division between an Array and scalar : \n", DivideByScalar)

Output of product between an Array and scalar : 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Output of division between an Array and scalar : 
 [[0.125 0.25  0.375]
 [0.5   0.625 0.75 ]
 [0.875 1.    1.125]]


In [10]:
# Finding the maximum value in the matrix
import numpy as np
Array = np.matrix( [ [ 1, 2, 3 ],
                      [ 4, 5, 6 ],
                      [ 7, 8, 9 ] ] )

print("Max value in the matrix : ", np.amax(Array))
print("Max value in the matrix along axis 0 : ", np.amax(Array, axis=0))
print("Max value in the matrix along axis 1 : ", np.amax(Array, axis=1))

Max value in the matrix :  9
Max value in the matrix along axis 0 :  [[7 8 9]]
Max value in the matrix along axis 1 :  [[3]
 [6]
 [9]]


In [13]:
# Finding the min value in the matrix
import numpy as np
Array = np.matrix( [ [ 1, 2, 3 ],
                      [ 4, 5, 6 ],
                      [ 7, 8, 9 ] ] )

print("Min value in the matrix : ", np.amin(Array))
print("Min value in the matrix along axis 0 : ", np.amin(Array, axis=0))
print("Min value in the matrix along axis 1 : ", np.amin(Array, axis=1))


Min value in the matrix :  1
Min value in the matrix along axis 0 :  [[1 2 3]]
Min value in the matrix along axis 1 :  [[1]
 [4]
 [7]]
sum of matrix: 
 45
sum of matrix: 
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [20]:
import numpy as np
Array = np.matrix( [ [ 1, 2, 3 ],
                      [ 4, 5, 6 ],
                      [ 7, 8, 9 ] ] )
print("sum of matrix: \n", np.sum(Array))
print("sum of matrix: \n", np.square(Array))

sum of matrix: 
 45
sum of matrix: 
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [23]:
# Dot product
import numpy as np
Array1 = np.array([1, 2, 3])
Array2 = np.array([4, 5, 6])
print("Dot product : \n",np.dot(Array2 , Array1))

Dot product : 
 32


In [25]:
# cross product
import numpy as np
Array1 = np.array([1, 2, 3])
Array2 = np.array([4, 5, 6])
print("cross product : \n",np.cross(Array2 , Array1))

cross product : 
 [ 3 -6  3]


In [26]:
import numpy as np
a = [[1, 2], [2, 3]]
b = [[4, 5], [6, 7]]

print("Matrix A:")
print(a)
print("Matrix B:")
print(b)

c = np.dot(a, b)
print("Result:")
print(c)

Matrix A:
[[1, 2], [2, 3]]
Matrix B:
[[4, 5], [6, 7]]
Result:
[[16 19]
 [26 31]]


In [27]:
import numpy as np
x = [[1, 2, 3], [2, 3, 4], [4, 5, 6]]
y = [[4, 5, 1], [6, 7, 2], [7, 8, 9]]

print("Matrix X:")
print(x)
print("Matrix Y:")
print(y)

z = np.dot(x, y)
print("Result:")
print(z)

Matrix X:
[[1, 2, 3], [2, 3, 4], [4, 5, 6]]
Matrix Y:
[[4, 5, 1], [6, 7, 2], [7, 8, 9]]
Result:
[[ 37  43  32]
 [ 54  63  44]
 [ 88 103  68]]


In [28]:
import numpy as np
x = [[1, 2, 3], [2, 3, 4], [4, 5, 6]]
y = [[4, 5], [6, 7], [7, 8]]

print("Matrix X:")
print(x)
print("Matrix Y:")
print(y)

z = np.dot(x, y)
print("Result:")
print(z)

Matrix X:
[[1, 2, 3], [2, 3, 4], [4, 5, 6]]
Matrix Y:
[[4, 5], [6, 7], [7, 8]]
Result:
[[ 37  43]
 [ 54  63]
 [ 88 103]]


In [29]:
import numpy as np
x = [[1, 2, 3], [2, 3, 4], [4, 5, 6]]
y = [[4], [6], [7]]

print("Matrix X:")
print(x)
print("Matrix Y:")
print(y)

z = np.dot(x, y)
print("Result:")
print(z)

Matrix X:
[[1, 2, 3], [2, 3, 4], [4, 5, 6]]
Matrix Y:
[[4], [6], [7]]
Result:
[[37]
 [54]
 [88]]


In [30]:
import numpy as np
x = [[1, 2, 3], [2, 3, 4], [4, 5, 6]]
y = [[4, 5, 1,5], [6, 7, 2, 6], [7, 8, 9, 7]]

print("Matrix X:")
print(x)
print("Matrix Y:")
print(y)

z = np.dot(x, y)
print("Result:")
print(z)

Matrix X:
[[1, 2, 3], [2, 3, 4], [4, 5, 6]]
Matrix Y:
[[4, 5, 1, 5], [6, 7, 2, 6], [7, 8, 9, 7]]
Result:
[[ 37  43  32  38]
 [ 54  63  44  56]
 [ 88 103  68  92]]


In [32]:
# Cross product
import numpy as np
Array1 = np.array([1, 2, 3])
Array2 = np.array([4, 5, 6])
print("Cross product : \n",np.cross(Array2 , Array1))

Cross product : 
 [ 3 -6  3]


The code you executed calculates the cross product of two 3D vectors, Array2 and Array1.

Given:

Array1 = [1, 2, 3]
Array2 = [4, 5, 6]
When you calculate np.cross(Array2, Array1), the result is obtained using the following formula for two vectors A = [A1, A2, A3] and B = [B1, B2, B3]:

A x B = [A2*B3 - A3*B2, A3*B1 - A1*B3, A1*B2 - A2*B1]

In your case, with A = Array2 and B = Array1:

First component (x-component): (5 * 3) - (6 * 2) = 15 - 12 = 3
Second component (y-component): (6 * 1) - (4 * 3) = 6 - 12 = -6
Third component (z-component): (4 * 2) - (5 * 1) = 8 - 5 = 3
Therefore, the cross product Array2 x Array1 is [3, -6, 3], as shown in the output.

In [36]:
import numpy as np

# === MATRIX CREATION ===
print("=== Matrix Creation ===")

# Farm data: 3 plots, 4 factors each
# Columns: temp, rain, pH, fertilizer
farm_factors = np.array([
    [28, 150, 6.5, 50],
    [30, 120, 6.8, 45],
    [26, 180, 6.2, 60]])

print(f"Farm Factors (3x4):\n{farm_factors}")

# Weights for yield prediction
weights = np.array([[10], [5], [100], [20]])  # 4x1
print(f"\nWeights (4x1):\n{weights.flatten()}")

# === MATRIX MULTIPLICATION ===
print("\n=== Matrix Multiplication ===")

# Predicted yields = factors @ weights + base
base_yield = 1000
predicted_yields = farm_factors @ weights + base_yield
print(f"Predicted Yields:\n{predicted_yields.flatten()}")

# === TRANSPOSE ===
print("\n=== Transpose ===")
print(f"Original shape: {farm_factors.shape}")
print(f"Transposed shape: {farm_factors.T.shape}")
print(f"Transposed:\n{farm_factors.T}")

# === ELEMENT-WISE VS MATRIX OPERATIONS ===
print("\n=== Element-wise vs Matrix ===")
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(f"A * B (element-wise):\n{A * B}")
print(f"A @ B (matrix multiply):\n{A @ B}")

# === PRACTICAL: NUTRIENT CALCULATION ===
print("\n=== Fertilizer Mix Calculation ===")
# NPK requirements per crop (kg/ha)
npk_needs = np.array([
    [120, 60, 40],   # Wheat
    [100, 50, 50],   # Rice
    [80, 40, 30]])   # Millet

# Area of each crop (hectares)
areas = np.array([[5], [3], [2]])  # Column vector

# Total NPK needed = crops × areas
total_npk = npk_needs.T @ areas
print(f"Total N needed: {total_npk[0][0]} kg")
print(f"Total P needed: {total_npk[1][0]} kg")
print(f"Total K needed: {total_npk[2][0]} kg")

=== Matrix Creation ===
Farm Factors (3x4):
[[ 28.  150.    6.5  50. ]
 [ 30.  120.    6.8  45. ]
 [ 26.  180.    6.2  60. ]]

Weights (4x1):
[ 10   5 100  20]

=== Matrix Multiplication ===
Predicted Yields:
[3680. 3480. 3980.]

=== Transpose ===
Original shape: (3, 4)
Transposed shape: (4, 3)
Transposed:
[[ 28.   30.   26. ]
 [150.  120.  180. ]
 [  6.5   6.8   6.2]
 [ 50.   45.   60. ]]

=== Element-wise vs Matrix ===
A * B (element-wise):
[[ 5 12]
 [21 32]]
A @ B (matrix multiply):
[[19 22]
 [43 50]]

=== Fertilizer Mix Calculation ===
Total N needed: 1060 kg
Total P needed: 530 kg
Total K needed: 410 kg


In [37]:
# True Inverse of NumPy Matrix
import numpy as np
Array = np.array([[2, 2, 1],
               [1, 3, 1],
               [1, 2, 2]])
print("Array = ")
print(Array)
print("\nDeterminant:", np.linalg.det(Array))
print("\nInverse of Array = ")
print(np.linalg.inv(Array))

Array = 
[[2 2 1]
 [1 3 1]
 [1 2 2]]

Determinant: 4.999999999999999

Inverse of Array = 
[[ 0.8 -0.4 -0.2]
 [-0.2  0.6 -0.2]
 [-0.2 -0.4  0.8]]
